export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR';
export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export const UPDATE_QUESTIONS_SUCCESS = 'UPDATE_QUESTIONS_SUCCESS';
export const UPDATE_CURRENT_QUESTION_SUCCESS = 'UPDATE_CURRENT_QUESTION_SUCCESS';
export const GET_TRANSLATIONS_SUCCESS = 'GET_TRANSLATIONS_SUCCESS';


